include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - missing_type_annotation
    - prefer_const_constructors
    - prefer_const_declarations
    - public_member_api_docs
